import React from 'react';
import { X, Printer, Download, ShieldCheck, AlertOctagon, Hash, Calendar, FileText, CheckCircle2 } from 'lucide-react';

export const DossierModal = ({ isOpen, onClose, preset }) => {
  if (!isOpen) return null;

  const handlePrint = () => {
    window.print();
  };

  const isPass = preset.statusType === 'authentic';

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs overflow-y-auto">
      <div className="relative w-full max-w-4xl bg-white rounded-xl shadow-2xl border border-slate-300 overflow-hidden my-8">
        
        {/* Modal Top Action Bar */}
        <div className="flex items-center justify-between px-6 py-3 bg-slate-900 text-white border-b border-slate-800 no-print">
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyan-400" />
            <span className="font-mono font-bold text-sm">
              Official Forensic Audit Dossier (SIH26188)
            </span>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-cyan-700 hover:bg-cyan-800 text-white text-xs font-bold transition-colors"
            >
              <Printer className="w-4 h-4" />
              <span>Print / Save PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Dossier Sheet */}
        <div className="p-8 space-y-6 text-slate-900 font-sans text-xs">
          {/* Header Banner */}
          <div className="border-b-2 border-slate-900 pb-4 flex items-start justify-between">
            <div>
              <div className="text-[11px] font-mono text-cyan-800 font-bold tracking-widest uppercase">
                Ministry of Home Affairs • Border Control & Immigration
              </div>
              <h2 className="text-xl font-black text-slate-900 tracking-tight mt-0.5">
                AI DOCUMENT FORENSIC AUDIT DOSSIER
              </h2>
              <div className="text-xs text-slate-500 font-mono mt-1">
                Generated by AuthenSight Forensic Screening Node (SIH26188-BLR)
              </div>
            </div>

            <div className="text-right">
              <div className="inline-block px-3 py-1 rounded border text-xs font-mono font-black uppercase mb-1">
                {isPass ? (
                  <span className="text-emerald-700 bg-emerald-50 border-emerald-300 px-2 py-0.5 rounded">
                    ✓ STATUS: CLEARED (96/100)
                  </span>
                ) : (
                  <span className="text-rose-700 bg-rose-50 border-rose-300 px-2 py-0.5 rounded">
                    ⚠️ STATUS: FORGERY LOGGED ({preset.trustScore}/100)
                  </span>
                )}
              </div>
              <div className="text-[10px] font-mono text-slate-500">
                Timestamp: 2026-09-04 19:50:00 UTC+05:30
              </div>
            </div>
          </div>

          {/* Document & Subject Metadata Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 bg-slate-50 p-4 rounded-lg border border-slate-200 font-mono text-[11px]">
            <div>
              <span className="text-[9px] text-slate-400 block uppercase">Document Type</span>
              <span className="font-bold text-slate-800 uppercase">{preset.idType}</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-400 block uppercase">Document Number</span>
              <span className="font-bold text-cyan-800">{preset.documentNumber}</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-400 block uppercase">Subject Full Name</span>
              <span className="font-bold text-slate-800">{preset.holderName}</span>
            </div>
            <div>
              <span className="text-[9px] text-slate-400 block uppercase">Date of Birth</span>
              <span className="font-bold text-slate-800">{preset.dob}</span>
            </div>
            <div className="col-span-2 sm:col-span-4 border-t border-slate-200 pt-2 flex items-center justify-between text-[10px]">
              <span className="text-slate-500 flex items-center gap-1">
                <Hash className="w-3 h-3 text-cyan-700" />
                SHA-256 Optical Hash:
              </span>
              <span className="font-mono text-slate-700 font-semibold truncate max-w-[450px]">
                {preset.sha256}
              </span>
            </div>
          </div>

          {/* Validation Scorecard Summary */}
          <div>
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider mb-2 font-mono">
              Itemized Diagnostic Findings
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {Object.entries(preset.checks).map(([k, v]) => (
                <div key={k} className="border border-slate-200 rounded p-3 bg-white">
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="font-bold text-slate-900 text-xs">{v.title}</span>
                    <span className={`text-[10px] font-mono font-bold px-1.5 py-0.2 rounded ${v.status === 'pass' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800'}`}>
                      {v.score}
                    </span>
                  </div>
                  <p className="text-[10px] text-slate-600 font-mono leading-relaxed mb-2">
                    {v.explanation}
                  </p>
                  <div className="space-y-1 border-t border-slate-100 pt-1.5 text-[9.5px]">
                    {v.details.map((d, i) => (
                      <div key={i} className="flex justify-between text-slate-600">
                        <span>{d.label}:</span>
                        <span className={d.pass ? 'text-emerald-700 font-bold' : 'text-rose-600 font-bold'}>
                          {d.value}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Inspector Incident Notes & Signoff */}
          <div className="border border-slate-200 rounded-lg p-4 bg-slate-50">
            <h4 className="text-xs font-bold text-slate-900 uppercase font-mono mb-1">
              Officer Adjudication Directive
            </h4>
            <p className="text-xs font-mono text-slate-700 leading-relaxed mb-4">
              {preset.inspectorSummary}
            </p>
            <div className="flex items-center justify-between border-t border-slate-200 pt-3 text-[10px] font-mono text-slate-600">
              <div>
                <span className="font-bold text-slate-900 block">Inspector ID: INSP-4091</span>
                <span>Officer K. Sharma • Border Node Delhi Terminal 3</span>
              </div>
              <div className="text-right">
                <span className="font-bold text-emerald-700 block">CRYPTOGRAPHICALLY SIGNED</span>
                <span>SHA-512 Hash Verified • PKI Root Key</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
